services:
  redis:
    image: redis:7-alpine
    container_name: flash-sale-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flash-sale-network

  postgres:
    image: postgres:16-alpine
    container_name: flash-sale-postgres
    environment:
      POSTGRES_USER: flash_sale_user
      POSTGRES_PASSWORD: flash_sale_password
      POSTGRES_DB: flash_sale_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U flash_sale_user -d flash_sale_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - flash-sale-network

volumes:
  redis-data:
  postgres-data:

networks:
  flash-sale-network:
    driver: bridge
